name: Docker Image

on:
  push:
    branches: ["main"]

jobs:
  buildservice:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: generate buildnumber
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: checkout service
        uses: actions/checkout@v2
        with:
          path: service
      - name: read docker properties
        uses: madhead/read-java-properties@latest
        id: docker
        with:
          file: service/docker.properties
          all: true
      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service
          push: true
          tags: |
            jfcbxp/${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
            jfcbxp/${{ steps.docker.outputs.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARTIFACT_NAME=${{ steps.docker.outputs.ARTIFACT_NAME }}
            IMAGE_VERSION=${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}
